name: Build, Push, and Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using credentials stored in secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Real-Estate-Business-API/Dockerfile # Path to your Dockerfile
          push: true
          tags: s0k1l/realestatebusinessapi:latest

      # Step 4: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
              "image": "s0k1l/realestatebusinessapi:latest"
            }' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
